---
title: How does a CPU work? Overview
date: 2020-12-20
tags: draft
category:
link:
description:
---

== Wie funktioniert eine CPU - Inhaltsverzeichnis

== *Einführung und Überblick*

_Einführung und Überblick_

Jedes Thema dieses Kurses ist in zwei Teile gegliedert:
Ein Teil über die mathematische Seite der digitalen Logik,
idealerweise fast unabhängig von den Implementierungsdetails
und einen konkreteren Teil, der genau diese Details behandelt.
Im konkreten Teil werden wir hauptsächlich die Implementierung
auf der elektrischen Ebene diskutieren, obwohl es auch andere Lösungen
gibt, die zum Beispieil auf
https://erik-engheim.medium.com/microprocessors-running-on-air-a47a702dd41f[Fluiddynamik],
oder https://www.photonics.com/Articles/All-Optical_Logic_Gates_Show_Promise_for_Optical/a63226[optische Gatter]
beruhen. die meisten Computer und Logikgatter jedoch basieren immer noch
auf Elektronik und Halbleitertechnologie, und das wird sich auch mit  dem
https://www.azom.com/article.aspx?ArticleID=17173[Quantencomputer],welche  größtenteils
an die Wahrscheinlichkeitstheorie gebunden ist nicht substantiell ändern.Jedoch werden sich mit dem Quantencomputing
werden sich jedoch die Grundlagen, die der Autor hier beschreibt, komplett ändern.

== *Kombinatorische Logik*
_https://wehrend.uber.space/docs/digital_logic/00_combinatorial_logic[Einführung in die kombinatorische Logik]_

Kurze Einführung in die kombinatorische Logik und ihre verschiedenen Beschreibungsmodelle.

== *Ein erster Blick auf die digitale Logik*

_https://wehrend.uber.space/docs/digital_logic/01_boolean_algebra/[Boolesche Algebra, grundlegende logische Gatter und ihre Implementierung]_

In dieser Lektion lernen wir Wahrheitstabellen und die boolesche Notation kennen und erfahren etwas über
De Morgans Gesetze.
Außerdem werfen wir einen Blick auf die grundlegendsten Logikgatter und warum sie in der Elektronik normalerweise nicht als solche implementiert werden.
in der Elektronik nicht als solche implementiert werden, sondern als NAND- und NOR-Gatter.

== *Sie müssen sich entscheiden!*

_https://wehrend.uber.space/docs/digital_logic/02_xor/[Ein komplexes Gatter: XOR]_

Eine weitere CPU-Anweisung und als Nebenbemerkung und Vorbereitung auf das nächste Thema,
werfen wir einen Blick auf das XOR-Gatter. Wie in der ersten Lektion sehen wir uns zuerst den logischen
Teil und dann seine Übersetzung in eine elektrische Implementierung.


== *01+01 = 10*

_http://wehrend.uber.space/docs/digital_logic/03_binary_system/[Binäre Systeme (Teil I) und Kombinatorische Logik (Teil I)]_

Hier erklären wir das Grundkonzept des Zählens mit nur zwei verschiedenen Zuständen.
Außerdem lernen wir, wie man zwei positive ganze Zahlen im Binärsystem addiert, die
die für eine Volladdierung benötigte Logik ableiten, um dann in das Thema der kombinatorischen Logik einzutauchen.

== *Es gibt viel Platz im negativen Raum*

_http://wehrend.uber.space/docs/digital_logic/04_signs/[Binärsystem (Teil II) Vorzeichenbehaftete ganze Zahl]_

Zweiter Teil über das Binärsystem. In diesem Beitrag lernen wir über die Ein- und Zwei
Komplement und Subtraktion.


== *Addieren ist nicht alles*

_http://wehrend.uber.space/docs/digital_logic/05_alu/[Kombinatorische Logik (Teil II), eine einfache ALU]_

Mit diesem zweiten Kapitel über kombinatorische Logik wollen wir die erste Serie abschließen.
Wir werden den Addierer zu einer einfachen ALU erweitern


== *Übersicht, was als nächstes kommt*

Vom Kombinatorischen zum Sequentiellen_

In diesem ersten Kurs haben wir einige Grundlagen über digitale Logik gelernt. Aber all diese Beispiele
verwenden nur statische Logik, uns fehlt noch ein Konzept, wie man berechnete Werte speichert.
Wir müssen das Konzept der Register und der sequentiellen Logik lernen.
Dies wird das Hauptthema der zweiten Beitragsserie sein.


== Extra

== *Lass mich das nachschlagen*

_Erster Blick in den Speicher und Look-Up-Tables (LUTs)_

In dieser Lektion lernen wir, dass - im Prinzip - jede Form von kombinatorischer Logik
in 'Software' umgewandelt werden kann, indem man sie im Speicher ablegt. In einem praktischen Beispiel werden wir
zeigen wir, wie ein DDS-Sinuswellengenerator eine Look-Up-Table (LUT) verwendet, um den Sinus zu replizieren.


