---
title: 01_boolean_algebra
date: 2020-12-23
tags:
math:
category:
link:
description:
type: text
menu:
  docs:
    parent: "digital_logic"
    identifier: "01_boolean_algebra"
    weight: 5
---
== Boolesche Algebra und einfache logische Gatter

Wir beginnen (die Reise) mit drei sehr
grundlegenden logischen Funktionen (oder Operationen), die trotz ihrer Einfachheit
bereits gültige Anweisungen einer regulären CPU sind:

*NOT, AND und OR*.


Logische Funktionen - auch Operationen genannt, der Autor wird hier beide Begriffe abwechselnd verwenden -
können auf verschiedene Weise beschrieben werden, am häufigsten wird sie implizit beschrieben
als boolesche Gleichung, aber sie können auch explizit in einer Wahrheitstabelle erklärt werden.

Eine Wahrheitstabelle ist eine Tabelle mit einer Spalte für jede Eingabe und einer Spalte für jede Ausgabe.
Sie zeigt also die Ausgabe bzw. die Ausgänge der Funktion für alle möglichen Kombinationen von Eingaben.
Sie kann auch Spalten mit Zwischenwerten enthalten.

Die in dieser Lektion gezeigten Wahrheitstabellen sind im Allgemeinen sehr klein und zeigen nur Kombinationen von zwei Eingaben,
obwohl alle Funktionen, die Eingänge verbinden, auf eine beliebige Anzahl von Eingängen erweitert werden können.

Boolesche Gleichungen können in Wahrheitstabellen umgewandelt werden und umgekehrt. Später werden wir auch einführen
https://en.wikipedia.org/wiki/Karnaugh_map[Karnaugh-Maps], eine Möglichkeit, die boolesche Logik auf grafische Weise zu optimieren.

=== NICHT
Die Nicht-Operation wird auch als Inversion bezeichnet,
wird bezeichnet als \[\overline{A} = \neg A = Q\]



[width=„50%“ cols=„1,1“]
|==========
| A | Q
| 0 | 1
| 1 | 0
|==========

image:../images/how_does_cpu/inverter_symbol.svg[width=200]

Die Operation not ist die einzige mit nur einem Eingang, sie kann nicht erweitert werden.

Dementsprechend ist die Gate-Level-Implementierung auch unter dem Namen Inverter bekannt.
Trotz seiner scheinbar einfachen Funktionalität gibt es über den Inverter viel zu sagen
sowohl zur Logik als auch zur Implementierung zu sagen, so dass der Autor ihm einen eigenen
Beitrag in der Mitte des Features widmen.

=== UND

Die und-Verknüpfung, auch als Konjunktion bezeichnet
wird als \[A \land B = Q\] bezeichnet

[width=„50%“ cols=„1,1,1“]
|================
| A | B | Q
| 0 | 0 | 0
| 0 | 1 | 0
| 1 | 0 | 0
| 1 | 1 | 1
|================


image:../images/how_does_cpu/and_symbol.svg[width=200]

=== ODER

Die Oder-Operation, auch als Disjunktion bezeichnet
wird als \[A \lor B = Q\] bezeichnet

[width=„50%“ cols=„1,1,1“]
|================
| A | B | Q
| 0 | 0 | 0
| 0 | 1 | 1
| 1 | 0 | 1
| 1 | 1 | 1
|================

image:../images/how_does_cpu/or_symbol.svg[width=200]

////
=== XOR

Die Exklusiv-Oder-Operation xor, die auch als Antivalenz bezeichnet wird
wird bezeichnet als A ⊕ B = Q

[width=„50%“]
|================
| A | B | Q
| 0 | 0 | 0
| 0 | 1 | 1
| 1 | 0 | 1
| 1 | 1 | 0
|================

image:../images/how_does_cpu/xor_symbol.svg[width=200]

Es gibt eine Menge wichtiger Anwendungen für die Exklusiv-Oder-Operation
wie man es von einer so grundlegenden und grundlegenden Operation erwarten kann, aber dennoch
ist die Situation bei dieser Operation ein wenig anders als bei 'und' und 'oder'.

////

'''

Obwohl die boolesche Algebra an sich schon ein interessantes Gebiet ist, werden wir das Thema hier nur kurz anreißen, gerade genug
um ein Gefühl und ein Verständnis dafür zu bekommen, wie man mit booleschen Formeln arbeitet.

[HINWEIS]
Wenn Sie an einer tiefer gehenden Betrachtung interessiert sind, die Induktion und Beweise enthält,
verweise ich Sie auf entsprechende Literatur (Quellen am Ende aufgeführt).


Die Gesetze der booleschen Algebra sind in der folgenden Tabelle dargestellt:
[%autowidth cols=„40,75a,75a“,options=„header“]
|====================================================================================================================
| Gesetz | ∧ (Konjunktion, UND-Operator) | ∨ (Disjunktion, ODER-Operator)
| Kommutativgesetz | ∨ (Konjunktion, UND-Operator) | ∨ (Disjunktion, ODER-Operator)
| Assoziativgesetz |
\[p \land (q \land r) = (p \land q) \land r = pqr\] |\[p \lor (q \lor r) = (p \lor q) \lor r = p \lor q \lor r\]
| Absorptionsgesetz | \[p \land (p \lor q) = p\]| \[p \lor (p \land q) = p\]
| Verteilungsgesetz | \[p \lor (q \lor r) = (p \land q) \lor (p \land r) = pq \lor pr\] |
\[p \lor (q \lor r) = (p \lor q) \lor (p \lor r) = (p \lor q)(p \lor r)\]
| neutrale Elemente | \[p \land 1 = p\] | \[p \lor 0 = p\]
| Komplementäres Element | \[p \land \neg p = 0\] | \[p \lor \neg p = 1\] |
*Referenz* |
*Hans-Jochen Bartsch* |
*Taschenbuch Mathematischer Formeln, 20. Auflage, S. 27- 28* |
|====================================================================================================================

Sie kennen wahrscheinlich intuitiv - oder aus der Schule - die ersten beiden in der Tabelle genannten Gesetze,
das Kommutativgesetz und das Assoziativgesetz.
Wie Sie sehen, kann jedes Gesetz sowohl auf Konjunktionen als auch auf Disjunktionen angewandt werden, ohne dass es Ausnahmen gibt.

Das Kommutativgesetz besagt, dass die Reihenfolge der Variablen für die Operation neutral ist und vertauscht werden kann, ohne
ohne das Ergebnis der Operation zu verändern.

Das Assoziativgesetz besagt, dass Klammern vertauschbar sind. Konjunktionen können ohne Operator kondensiert werden.

Das Absorptionsgesetz ist Ihnen wahrscheinlich aus der Schule nicht bekannt, da es nur in der Logik verwendet wird und
zumindest in der Schulmathematik kein Gegenstück hat.

Das Distributivgesetz wiederum ist aus der Schule bekannt. Es besagt, dass Variablen/Operationen außerhalb der Paranthese
auf alle Variablen in der Klammer angewendet werden müssen.

Das Gesetz der neutralen Elemente ist wiederum etwas Besonderes für die boolesche Algebra. Die logische Eins ist die Entsprechung zu 'wahr',
und somit ist p und wahr gleich 'wahr', so wie die logische Null 'falsch' ist und somit p oder falsch gleich p ist.

Das Komplementärgesetz besagt, dass es zu jedem Element (Variable) p ein komplementäres Element (Variable) [overline]#p# gibt,
so dass die Konjunktion zu einer logischen Null und die Disjunktion zu einer logischen Eins führt.

'''

An dieser Stelle muss der Autor ein wenig vorpreschen, denn einige praktische Fragen auf der elektrischen Ebene erfordern einige Überlegungen auf ihrer
Logik-Ebene:
Auf der Implementierungsebene (für eine elektrische Implementierung) ist es eher unüblich, AND, OR und NOT direkt zu verwenden, stattdessen
werden die Umkehrfunktionen NAND und NOR verwendet.


=== NAND und NOR

Die NAND-Operation wird als \[\overline{A \land B} = Q\] bezeichnet
während die NOR-Operation als \[\overline{A \lor B} = Q\] bezeichnet wird.


[width=„100%“ cols=„a,a“]
|======
| NAND | NOR
|image:../images/how_does_cpu/nand_symbol.svg[width=200] |image:../images/how_does_cpu/nor_symbol.svg[width=200]
|======

Wie Sie sehen können, sind die Ergebnisse für diese beiden Funktionen genau umgekehrt zu ihrem jeweiligen Komplement
(NAND <==> AND,NOR <==> OR), in diesem Sinne empfiehlt der Autor die Konstruktion der entsprechenden Wahrheitstabellen
als eine Übung für den Leser.



== Das De-Morgan-Theorem

Zusätzlich zu den oben eingeführten Grundaxiomen gibt es das **De-Morgan-Theorem**,
das wir benötigen, um auf einfache Weise zwischen NAND und NOR zu konvertieren. Der Einfachheit halber zeigen wir nur für
zwei Elemente, jedoch ist das Theorem unabhängig von einer beliebigen Anzahl von Elementen/Eingängen.

[„latex“, „../images/demorgan_nand.svg“,imgfmt=„svg“, width=„75%“]
\[\overline{p_1 \land p_2} = \overline{p_1} \lor \overline{p_2}\]

[width=„100%“ cols=„a,a,25a,25a,25a,25a“]
|==========================================================================================
| A | B |\[\overline{A}\] | \[\overline{B}\] | \[\overline{AB}\] |\[\overline{A} \lor \overline{B}\]
| 0 | 0 | 1 | 1 | 1 | 1
| 0 | 1 | 1 | 0 | 1 | 1
| 1 | 0 | 0 | 1 | 1 | 1
| 1 | 1 | 0 | 0 | 0 | 0
|==========================================================================================




image:../images/how_does_cpu/de_morgan_nand_equivalence.svg[width=400]


[„latex“, „../images/demorgan_nor.svg“,imgfmt=„svg“, width=„75%“]
\[\overline{p_1 \lor p_2} = \overline{p_1} \land \overline{p_2}\]


[width=„75%“ cols=„a,a,25a,25a,25a,25a“]
|==========================================================================================
| A | B |\[\overline{A}\] | \[\overline{B}\] | \[\overline{AB}\]| \[\overline{A} \lor \overline{B}\]
| 0 | 0 | 1 | 1 | 1 | 1
| 0 | 1 | 1 | 0 | 0 | 0
| 1 | 0 | 0 | 1 | 0 | 0
| 1 | 1 | 0 | 0 | 0 | 0
|==========================================================================================


image:../images/how_does_cpu/de_morgan_nor_equivalence.svg[width=400]



Nun sind wir endlich gerüstet, um mit dem elektrischen Teil / der Beschreibung fortzufahren.

== Umsetzung auf elektrischer Ebene

Zunächst stellen wir einige gängige elektronische Bauteile und ihre Symbole vor, die in
elektrischen Schaltplänen verwendet werden.

image:../images/how_does_cpu/common_symbols.svg[width=500]

Aus dem englischen übersetzt mit DeepL.com


=== Die Diode

Wir beginnen die Reise mit einem vereinfachten Schaltungsentwurf für 'und' und 'oder', der verdrahteten Logik.
Dieser Schaltungsentwurf ist so einfach, dass es nicht einmal möglich ist, einen Inverter darin zu implementieren.


[width=„100%“ cols=„100a,100a“]
|======
| verdrahtet und | verdrahtet oder
|image:../images/how_does_cpu/wire_and.svg[width=250] | image:../images/how_does_cpu/wire_or.svg[width=250]
| # diodes: 2 | # diodes : 2
|======

Wie Sie sehen können, ist diese Schaltung nicht allzu kompliziert - selbst Laien in Elektronik sollten in der Lage sein, die wesentlichen Teile zu erkennen
von - die Eingänge sind mit je einer Diode verbunden. Eine Diode ist ein einfacher Halbleiter, der als Einbahnstraße für elektrischen Strom dient.
Halbleiter sind eine Gruppe von Materialien (nur Silizium und Germanium sind hier aufgrund ihrer chemischen Eigenschaften sinnvoll),
die nicht wirklich leiten, aber auch keine Isolatoren sind. Vielmehr ist die Leitfähigkeit des Materials abhängig von der gezielten Verschmutzung
ihrer Kristallgitterstruktur mit Elementen der fünften Hauptgruppe, für ein n(egativ)-gepunktetes Material bzw. der dritten Hauptgruppe
für ein p(ositiv)-gepunktetes Material. Dieser Vorgang wird als Punktierung bezeichnet. Für den interessierten Leser https://www.electrical4u.com/semiconductor-physics/[hier]
ist ein Link zu allen physikalischen Hintergründen, die der Autor zu faul war zu wiederholen, da sie schon oft und besser im Internet erklärt sind ;-) .

image:../images/how_does_cpu/diode_structure.svg[width=450]

Alles, was wir wissen müssen, ist, dass eine Diode aus einem Substrat (in den meisten Fällen heute Silizium) besteht, das auf der einen Seite n-dottiert und auf der anderen Seite p-dottiert wird,
und dazwischen einen pn-Übergang bildet, der als besagte Einwegbarriere fungiert: Es ist möglich, dass Elektronen von der n-Seite zur p-Seite eilen, jedoch nicht andersherum.

Die zweite Komponente der oben gezeigten Schaltungen ist ein Widerstand, dessen einziger Zweck es ist, den fließenden Strom zu reduzieren.
Bei wire-and ist er als Pull-up-Widerstand verdrahtet, während er bei wire-or als Pull-down-Widerstand verdrahtet ist.
Der wire-and erreicht nur dann einen ausreichend hohen Pegel, wenn alle Eingänge auf High-Pegel gehen. Ähnlich geht der wire-or nur dann auf Low-Pegel, wenn keiner der Eingänge auf High-Pegel geht.
Um zu verhindern, dass Strom vom Pull-up-Widerstand zum Ausgang der vorherigen Schaltung (Wire-and) bzw. Strom von einem Eingang zurück zum anderen fließt, ist der Wire-or als Pull-down-Widerstand zu beschalten.
Um zu verhindern, dass Strom von einem Eingang zurück zum anderen Eingang (wire-or) fließt, sind die Dioden vorhanden.

Ein Problem dieses Aufbaus, auf das wir mit Sicherheit irgendwann stoßen werden, besteht darin, dass das Signal beim Übergang vom Eingang zum Ausgang schwach wird
und es gibt keine Möglichkeit, das Signal wiederherzustellen, so dass der Signalpegel am Ausgang von der nachfolgenden Schaltung möglicherweise nicht richtig unterschieden werden kann.
Erlauben Sie dem Autor an dieser Stelle eine Anmerkung zu einem feinen Detail in der Terminologie: Obwohl es oft als Verstärkung bezeichnet wird, wollen wir hier festhalten, dass wir einen
etwas „intelligenten“ Signalverstärker, der den Signalpegel des Eingangssignals erkennt und wiederherstellt, komplementär zu einem „dummen“ Verstärker, der einfach nur
der das Eingangssignal verstärkt.

Die Dioden sind also ein feines Bauteil, z.B. nützlich, um Teile der Schaltung vor elektrostatischer Entladung zu schützen
(https://www.allaboutcircuits.com/textbook/semiconductors/chpt-9/electrostatic-discharge/[ESD]), aber für unsere Logik ist sie nicht ausreichend.

Was wäre, wenn wir ein Bauteil hätten, das das Signal verstärken könnte, so dass wir Schaltungen entwerfen könnten, die auch die Signalpegel damit wiederherstellen?
Glücklicherweise gibt es ein solches Bauteil und es wird im nächsten Abschnitt vorgestellt.

////
//=== Der klassische Transistor
//
//Vor der eigentlichen Einführung des Transistors wollen wir einen Blick in die Geschichte werfen. Einige der ersten Computer, die gebaut wurden, benutzten
//http://www.historicsimulations.com/ZuseZ3.html[elektromechanische Relais],
///Während andere sich auf https://www.thoughtco.com/history-of-the-eniac-computer-1991601[Vakuumröhren] verließen.
//Die allerersten waren rein https://www.fourmilab.ch/babbage/[mechanisch].
//Hier wollen wir uns auf die Vakuumröhren - insbesondere die Triode - als Blackboxen konzentrieren, da das Funktionsprinzip äußerlich in etwa mit dem einer
//einem normalen / klassischen bipolaren Transistor.
//
//[width=„100%“ cols=„a,a“]
//|======
//|Bipolar Junction Transistor (BJT) | Triode (bestimmte Art von Vakuumröhre)
//||Bild:../images/how_does_cpu/bjt_structure.svg[width=450] | Bild:../images/how_does_cpu/triode.svg[width=300]
    *>* Ein Strom an der Basis steuert den Strom zwischen Kollektor und Emitter
    *>* Eine Spannung am Gitter steuert den Strom zwischen Kollektor und Emitter
//|======
////


////
Ein Transistor ermöglicht die Durchführung der oben vorgestellten Operationen und ermöglicht gleichzeitig die Verstärkung des Signals.
Er ist ein Schaltelement, das mit einer Steuerspannung gesteuert werden kann, ähnlich wie ein elektromechanisches Relais,
bei dem ein kleiner Strom in einer Spule ein Magnetfeld aufbaut, das den Anker bewegt, um die Kontakte des Lastkreises zu schließen (oder zu öffnen, je nach Bauart)
die Kontakte des Lastkreises.
////

=== Der MOSFET-Transistor

Der Transistortyp, den wir hier vorstellen und verwenden wollen, ist ein MOSFET (Metal Oxid Semiconductor Field Effect Transistor) - im Gegensatz zum klassischen bipolaren Transistor.
Wie der Name schon sagt, ist ein MOSFET ein Transistor (oder Halbleiter), bei dem der Laststrom durch die Stärke des elektrischen Feldes gesteuert werden kann, das am Gate-Eingang erzeugt wird
//https://www.power-and-beyond.com/whats-the-difference-between-mosfet-and-bjt-a-909006/


image:../images/how_does_cpu/mosfet_model.svg[width=500]

Das obige Bild skizziert den prinzipiellen Aufbau eines Mosfets auf Silizium. Source und Drain sind beide mit einer eigenen n-Wanne verbunden, im p-gepunkteten Substrat,
während das Gate dazwischen durch eine dünne Siliziumdioxidschicht isoliert ist. Bei diskreten MOSFETs, die mit der Source verbunden sind, gibt es einen vierten Anschluss, der zum Substrat führt,
aber das ist im Moment nicht relevant.
Hinter der Funktionsweise eines MOSFET steckt eine Menge komplexer Physik, und wir wollen nur wissen, dass beim Anlegen einer Spannung am Gate ein elektrisches Feld induziert wird,
Dadurch entsteht ein Kanal zwischen Source und Drain, durch den Elektronen von der Source zum Drain fließen können. Je höher die Gate-Spannung, desto größer (breiter) ist der Kanal, desto mehr Elektronen
fließen (natürlich nur bis zu einer bestimmten Grenze). Und wenn die Gate-Spannung gleich Null ist, ist auch der Kanal nicht vorhanden.

image:../images/how_does_cpu/inverter_nmos.svg[width=500]

Übliche Symbole für MOSFETs, die in elektrischen Schaltplänen verwendet werden, sowie einige andere, die wir aufgrund des Kurses brauchen, sind unten dargestellt, einige haben mehr als nur eines, besonders der MOSFET hat eine Anzahl
von leicht unterschiedlichen Symbolen, die die Unterschiede in der physikalischen Komponente widerspiegeln.

image:../images/how_does_cpu/mosfet_symbols.svg[width=500]

Mit dem eingeführten MOSFET-Element und einem einzelnen Widerstand, einem Element, das den Stromfluss reduziert, können wir eine Inverterschaltung wie in der obigen Abbildung direkt umsetzen.
Source ist mit der Masse verbunden und Drain ist mit dem Inverterausgang und über einen hochohmigen Widerstand auch mit der Spannungsquelle verbunden. Das Gate ist der Eingang des Inverters.
Wenn die Spannung am Gate zu niedrig eingestellt ist, leitet der MOSFET nicht, so dass das am Ausgang vorhandene Potenzial für eine logische Eins ausreicht.
Wenn am Gate eine Spannung angelegt wird, wird der Drain-Source-Pfad des MOSFETs leitend, das am Ausgang vorhandene Potenzial bricht zusammen und fließt über den Drain-Source-Pfad ab.

image:../images/how_does_cpu/inverter_cmos.svg[width=500]

'''
Auf der elektrischen Ebene hat der Inverter zwei verschiedene Aufgaben zu erfüllen

1. Auffrischung des Signals (Pegel), das der Wechselrichter von der vorhergehenden Schaltung erhält
2. Die eigentliche Invertierung des Signals

Es gibt auch integrierte Schaltkreise, die als Puffer oder Treiber bezeichnet werden und sich ausschließlich der erstgenannten Aufgabe widmen; darauf werden wir in einem späteren Blogbeitrag / einer späteren Lektion eingehen.
Hier wollen wir uns nur auf den logischen Teil der Invertierung des Signals konzentrieren, obwohl dafür beide Funktionen gleich wichtig sind, weshalb sie in einer
Schaltung. Natürlich müssen die logischen Signale auch in anderen logischen Schaltungen - wie und und oder - aufgefrischt werden, aber in den meisten Fällen wird diese Aufgabe ausschließlich von
diese Inverterstufen erledigt, danach oder davor.

image:../images/how_does_cpu/inverter_symbol.svg[width=200]

Im Symbol wird die erste Aufgabe, das Auffrischen des Signals (Pegels), durch das Dreieck angedeutet, während der kleine Kreis die eigentliche Invertierungsfunktion kennzeichnet.
'''

[width=„100%“ cols=„a,a“]
|======
| NMOS NAND | NMOS NOR
|image:../images/how_does_cpu/nand_nmos.svg[width=200] | image:../images/how_does_cpu/nor_nmos.svg[width=500]
| # transistor: 2 | # transistor: 2
|======

Jetzt wird klar, warum die Umkehrfunktion von UND und ODER auf Gatterebene einfacher ist als die ursprüngliche Funktion.
Denn man muss nachträglich eine Inverterschaltung hinzufügen, wodurch sich die Anzahl der Transistoren erhöht.

Ein großer Nachteil der Implementierung ist der hohe Stromverbrauch, der durch den Pull-up-Widerstand verursacht wird. Wir wollen sehen, ob es eine Möglichkeit gibt
dieses Problem zu lösen. Was wäre, wenn es einen Transistor mit der Bezeichnung PMOS mit einer komplementären Struktur - p-Wells auf einem n-gepunkteten Substrat - zu unserer
bisher verwendeten NMOS-Schaltung?

Wenn wir diese anstelle des Widerstands für den Pull-up-Pfad verwenden, können wir die Verlustleistung drastisch reduzieren.
Wie Sie sich denken können, gibt es diese Technik, bei der beide Transistortypen kombiniert werden, unter der Bezeichnung CMOS (Complementary Metal Oxid Semiconductor).

[width=„100%“ cols=„a,a“]
|======
| CMOS NAND | CMOS NOR
|image:../images/how_does_cpu/nand_cmos.svg[width=250] | image:../images/how_does_cpu/nor_cmos.svg[width=500]
| # transistor: 4 | # transistor: 4
|======

////
//===Von diskret zu Silizium
////

Es wird nun deutlich, woher die CMOS-Technologie ihren Namen hat:
Wie wir bei der Umsetzung von NAND und NOR in CMOS-Technologie sehen können, ist die P-Schaltung oben genau das Komplementär der N-Schaltung unten.
Für den Inverter war diese Eigenschaft aufgrund der Symmetrie einfach nicht erkennbar.
Aber wir können auch den Nachteil der CMOS-Technologie erkennen: Die Anzahl der Transistoren verdoppelt sich, was den Aufwand und die Komplexität des Herstellungsprozesses erhöht
(komplexere Masken und Layouts, mehr Verarbeitungsschritte aufgrund verschiedener Transistortypen, nmos und pmos auf einem Wafer) und der integrierten Schaltung als Endprodukt.

Die Toolchain, der CMOS-Prozess und die damit verbundenen Technologien sind jedoch bereits seit Jahrzehnten weiterentwickelt und ausgereift, so dass dies heute keine Rolle mehr spielt, im Gegenteil
vor kurzem veröffentlichte Google sogar das https://github.com/google/skywater-pdk[SkyWater Open Source PDK 130], ein sogenanntes Process Design Kit, das Elektroingenieuren
ein Tool(chain) zur Erstellung von Designs für anwendungsspezifische integrierte Schaltungen, die dann direkt in einem 130nm-Prozess hergestellt werden können.
Sie können mehr darüber lesen https://hackaday.com/2020/06/30/your-own-open-source-asic-skywater-pdf-plans-first-130-nm-wafer-in-2020/[hier auf Hackaday].

Das war ein erster kleiner Einblick in die boolesche Logik und ihre Umsetzung auf Silizium, natürlich gibt es viel mehr als nur ein Referenzdesign,
Auch haben wir uns noch nicht mit ESD-Messungen und Schutzschaltungen für die Ein- und Ausgänge beschäftigt.

Im nächsten Beitrag werfen wir einen Blick auf die Exklusiv-Oder (XOR)-Operation.

