---
title: 02_XOR
date: 2024-10-24
category:
link: 
description: 
type: text
menu:
  docs:
    parent: "digital_logic"
    weight: 10
---

== XOR

Da es viele wichtige Anwendungen für die Exklusiv-Oder (XOR) Operation gibt
ist ihr ein eigener Blog-Beitrag gewidmet. Zwei der wichtigsten sind:

- XOR-Operationen werden häufig in linearen rückgekoppelten Schieberegistern (LFSR) verwendet.
LFSR sind ein entscheidender Schritt in Scramblern bzw. Descramblern,
die in Sendern/Empfängern verwendet werden
- Teil eines Verschlüsselungsalgorithmus
- Und nicht zuletzt ein wichtiger Teil eines Halbaddierers.

////
//wie man es bei einer so grundlegenden und fundamentalen Operation erwarten kann, aber dennoch
//ist die Situation bei dieser Operation ein wenig anders als bei 'und' und 'oder'.
////

Die Exklusiv-Oder-Operation xor, die auch als Antivalenz bezeichnet wird
wird als A ⊕ B = Q bezeichnet. Ihre Wahrheitstabelle ist unten dargestellt

[width=„50%“]
|================
| A | B | Q
| 0 | 0 | 0
| 0 | 1 | 1
| 1 | 0 | 1
| 1 | 1 | 0
|================

image:../images/how_does_cpu/xor_symbol.svg[width=250]

[width=„100%“ cols=„a“]
|======
| CMOS XOR
|image:../images/how_does_cpu/xor_cmos.svg[width=800]
| # Transistor: 12
|======



== Einige Anwendungen

=== Linear Feedback Shift Register (LSFR)
Wie oben beschrieben, werden XOR-Gatter in linearen rückgekoppelten Schieberegistern (Linear Feedback Shift Registers, LFSR) verwendet.
LFSR werden häufig zur Erzeugung von Testmustern verwendet.
Der Autor hat ein einfaches Beispiel für ein 3-Bit-LFSR ausgewählt, das in einem
https://www.ti.com/lit/an/scta036a/scta036a.pdf[White Paper von Texas Instruments].


image:../images/how_does_cpu/lfsr.svg[width=800]

Für dieses Beispiel müssen wir einen großen Sprung machen und uns in den Bereich der sequentiellen Schaltungen begeben.
Das sind Schaltungen, die eine Rückkopplung nutzen. Das gewählte Beispiel erzeugt pseudo-zufällige
Testmuster entsprechend der untenstehenden Tabelle. Die Register werden mit dem Seed-Wert 111 gefüttert,
nach 8 Taktzyklen wiederholen sich die Muster erneut.
Echte Testmustergeneratoren haben natürlich eine viel höhere Bitbreite.

[width=„50%“]
|================
| CLK | FF1 | FF2 | FF3
| 0 | 1 | 1 | 1
| 1 | 0 | 1 | 1
| 2 | 0 | 0 | 1
| 3 | 1 | 0 | 0
| 4 | 1 | 0 | 0
| 5 | 0 | 1 | 0
| 6 | 1 | 0 | 0
| 7 | 1 | 1 | 0
| 8 | 1 | 1 | 1
|================

=== Halbaddierer
Im nächsten Blogpost tauchen wir tiefer in die Anwendung der Halbaddirer ein.
Die Halbaddierer bestehen im Wesentlichen aus den beiden folgenden Gleichungen
für die Summe (unter Verwendung des XOR ) und den Übertrag (unter Verwendung eines einfachen AND).

[„latex“,„../images/half-adder.svg“,imgfmt=„svg“, width=„40%“]
\[
\begin{array}{c}
c = x \land y \\
s = x \oplus y
\end{array}
\]


Übersetzt mit DeepL.com (kostenlose Version)