---
title: How does a CPU work 2? Overview
date: 2023-05-14
tags: ['draft']
category:
link:
description:
---

== Wie funktioniert eine CPU 2 - Inhaltsverzeichnis

== *Von kombinatorischer zu sequentieller Logik - Einführung*
_https://wehrend.uber.space/docs/digital_logic_2/10_sequential_logic[Einführung in sequentielle Logik]_

Wir gelangen von rein kombinatorischen Logikschaltungen ohne jegliche Form von Speicher zu sequentiellen Logikschaltungen mit irgendeiner
Art von Speicher (meistens Flipflops)

== *Uhren, Flipflops und Register*

_https://wehrend.uber.space/docs/digital_logic_2/11_clocks_and_registers/[Uhren, Flipflops und Register]_

Wir machen einen Sprung in den Bereich der sequentiellen Logik und führen einige für die sequentielle Logik wichtige Konzepte ein,
wie Uhr, Flipflops und Register

== *Automaten*

_https://wehrend.uber.space/docs/digital_logic_2/12_automata/[Automaten]_

Wir stellen die zwei (drei) verschiedenen Automaten Mealy, Moore (und Medwedjew) vor. Diese können synchron oder
asynchron sein.

== *CPU-Steuerung*

_http://wehrend.uber.space/docs/digital_logic_02/13_cpu_control/[CPU-Steuerung]_

Hier sezieren wir das Gehirn einer CPU, die Steuereinheit, die alle Aktionen
einer CPU handhabt und steuert.

== *Programmierbare Logik*

_http://wehrend.uber.space/docs/digital_logic_02/14_programmable_logic/[Programmierbare Logik]_

Wir stellen das Konzept der programmierbaren Logik sowohl für kombinatorische als auch sequentielle Logik vor.

== *Gründlich testen*

_http://wehrend.uber.space/docs/digital_logic_02/15_testable_logic/[Testable Logic]_

Jede eingebettete Schaltung oder Logik benötigt eine Infrastruktur zum Testen. Hier stellen wir
JTAG- und Boundary-Scan-Tests vor.

== *HDLs*

_VHDL und Verilog_

Wir stellen das Konzept einer Hardwarebeschreibungssprache (HDL) wie VHDL und Verilog vor.

= Extra

== *Register-Transfer-Level*

_Register-Transfer-Level_

In dieser Lektion stellen wir das Konzept des Register-Transfer-Levels vor.