---
title: X2_cordic
date: 2023-03-26
category:
link:
description:
tags: draft
type: text
menu:
  docs:
    parent: "digital_logic_3"
    identifier: "x2_cordic"
    weight: 35
---

== The CORDIC algoritm and direct digital synthesis (DDS)

The CORDIC (which stands for "coordinate rotation digital computer") algorithm, was developed in 1956 by Jack.E. Volder, to
replace the analog resolvers used for missiles navigation by digital computation on digital computer.
The algorithm turned out to be very successfull, today it can be found in every pocket calculator, doing
the computation of the trigonometrical functions sinus, cosinus and tangens. But the algorithm is not limited to that
it can also calculate logarithmic and exponential functions, given the needed modifications.

image:../images/unit_circle.svg[width=40%]

== The CORDIC algorithm
In the image below, V0 shows the start vector

["latex","../images/startvector.svg",imgfmt="svg", width="70%"]
\[v_{0}=\begin{bmatrix}
0 \\
1
\end{bmatrix}
\]

which we now iterate, by multiplying it with the rotation matrix, given below:
["latex","../images/vector_rotation.svg",imgfmt="svg", width="70%"]
\[v_{i+1}= R_i v_i\]

["latex","../images/vector_rotation.svg",imgfmt="svg", width="70%"]
\[ R_i = \begin{bmatrix}
cos(\theta) & -sin(\theta) \\
sin(\theta) & cos(\theta)
\end{bmatrix}
\]


image:../images/cordic_circle.svg[width=40%]

image:../images/dds_principle.svg[width=75%]


