name: Deploy Site

on:
  push:
    branches:
      - main
    # Adjust this filter if needed; it now triggers on any changes in the repo.
    paths:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: content

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          path: content

      - name: Änderungen im Repository prüfen
        id: content_changes
        run: |
          # Prüfe, ob sich etwas im geklonten Repository (im Ordner "content") geändert hat.
          if [ -n "$(git status --porcelain .)" ]; then
            echo "Content hat Änderungen."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Keine Änderungen gefunden."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Hugo
        if: steps.content_changes.outputs.changed == 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build der Site mit Hugo
        if: steps.content_changes.outputs.changed == 'true'
        run: hugo -D -d wehrend.github.io --config config.toml

      - name: 'Deployment: Commit und Push der Build-Änderungen'
        if: steps.content_changes.outputs.changed == 'true'
        working-directory: wehrend.github.io
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Änderungen im Build-Output erkannt – Deployment wird durchgeführt..."
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Automatischer Deployment-Commit"
            git push origin main
          else
            echo "Keine Änderungen im Build-Output zum Committen."
          fi
