name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
      TZ: Europe/Berlin

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb

      - name: Build Hugo site
        run: |
          hugo --gc --minify --source /home/runner/work/content
          ls -la wehrend.github.io

      - name: Deploy to GitHub Pages (via SSH)
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GH_DEPLOY_KEY }}
          external_repository: wehrend/wehrend.github.io
          publish_branch: main
          publish_dir: content/content/wehrend.github.io
          user_name: wehrend
          user_email: sven.wehrend@gmail.com
